[Interface]
# Bouncing = 3
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = AMnTr/UonkIi5vX0NQ2y9d2x/JVrO2oUXKKGAHXudmg=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# CA#1239
PublicKey = TiJHg8s/NAuWWqLWFEPWu1ARGMmeH4v2qmtUH4zZmC4=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 84.20.16.1:51820

PersistentKeepalive = 25
